### ISSUE TITLE
make call or  incoming call error

### ISSUE THREAD

**Issue by MrsZ** [StrikeForceZero/PJSIPDotNetSDK#1]
i have run this project，register successful。but when I make call or  incoming call ，IT error。

do you know this problem??

thanks  .

![image](https://user-images.githubusercontent.com/13742821/32213955-4bb3bdac-be58-11e7-88d7-f65adeb9d098.png)

**Comment by StrikeForceZero** [comment]
I haven't really given the test GUI much love since I created this but I'm guessing its a cross threading issue.

For [make call](https://github.com/StrikeForceZero/PJSIPDotNetSDK/tree/d5705e5329a2b00d70c0a74f12c18503b6d485c8/TestGui/MainWindow.xaml.cs#L181)

Try this:

```
private void MakeCallButton_Click(object sender, RoutedEventArgs e)
{            
    Application.Current.Dispatcher.BeginInvoke(
        DispatcherPriority.Normal,
        (ThreadStart)delegate()
        {
            sm.DefaultAccount.makeCall(PhoneNumberTextBox.Text);
        }
    );
}
```

**Comment by empire-tm** [comment]
> I haven't really given the test GUI much love since I created this but I'm guessing its a cross threading issue.
> 
> For [make call](https://github.com/StrikeForceZero/PJSIPDotNetSDK/tree/d5705e5329a2b00d70c0a74f12c18503b6d485c8/TestGui/MainWindow.xaml.cs#L181)
> 
> Try this:
> 
> ```
> private void MakeCallButton_Click(object sender, RoutedEventArgs e)
> {            
>     Application.Current.Dispatcher.BeginInvoke(
>         DispatcherPriority.Normal,
>         (ThreadStart)delegate()
>         {
>             sm.DefaultAccount.makeCall(PhoneNumberTextBox.Text);
>         }
>     );
> }
> ```

![image](https://user-images.githubusercontent.com/13998894/61631619-455f5380-aca4-11e9-8407-ac89de245d00.png)

I did not succeed, the problem remains. Please tell me what could be the matter?

**Comment by StrikeForceZero** [comment]
You might be using the outdated master branch, i just tried and it's working for me under this branch https://github.com/StrikeForceZero/PJSIPDotNetSDK/tree/dev/v1.0.x

**Comment by empire-tm** [comment]
> You might be using the outdated master branch, i just tried and it's working for me under this branch https://github.com/StrikeForceZero/PJSIPDotNetSDK/tree/dev/v1.0.x

I am incredibly happy! It works! Thank you very much!

**Comment by StrikeForceZero** [comment]
@MrsZ feel free to comment, so we can re-open this if you are still having issues
